// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PPYqJR7ZOq8K8NG2InI6WvBTu0gBtHU',
    appId: '1:443228942962:web:13288ffc5b392162dd48eb',
    messagingSenderId: '443228942962',
    projectId: 'vetika-vp-flutter',
    authDomain: 'vetika-vp-flutter.firebaseapp.com',
    storageBucket: 'vetika-vp-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_wgIEivhTko-sH4TWvumVivynxBt8RQ',
    appId: '1:443228942962:android:af552e5d6d55c038dd48eb',
    messagingSenderId: '443228942962',
    projectId: 'vetika-vp-flutter',
    storageBucket: 'vetika-vp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_BOFqbi3WHfUWWW06XcR65dz4O1IaE4',
    appId: '1:443228942962:ios:4c1a43989a724012dd48eb',
    messagingSenderId: '443228942962',
    projectId: 'vetika-vp-flutter',
    storageBucket: 'vetika-vp-flutter.appspot.com',
    iosClientId: '443228942962-1migu6j617jpkogjp63ll8me0jqnqd1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetikaMvpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR_BOFqbi3WHfUWWW06XcR65dz4O1IaE4',
    appId: '1:443228942962:ios:4c1a43989a724012dd48eb',
    messagingSenderId: '443228942962',
    projectId: 'vetika-vp-flutter',
    storageBucket: 'vetika-vp-flutter.appspot.com',
    iosClientId: '443228942962-1migu6j617jpkogjp63ll8me0jqnqd1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetikaMvpFlutter',
  );
}
